# -------------------------------------
# GeoPulse AI Secret Keys
# -------------------------------------
# Replace all "..." with your actual keys.

# --- 1. Signal API Keys ---
OPENWEATHER_API_KEY = "69207e84dfa4a7e9aae3e8e237aef9ee"
IQAIR_API_KEY = "ca944b2e-7583-4ea8-88a7-5926db590bad"
CALENDARIFIC_API_KEY = "enyqs4sy9TziTwH6alX5dN8AQWIVbVki"
NEWS_API_KEY = "738f9708489844998396ba29aef3f721"

# --- 2. AI Keys (Text & Image) ---
#OPENAI_API_KEY = "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"

# --- 3. Publisher Keys ---
TELEGRAM_BOT_TOKEN = "8541067576:AAGz80gTRb2Kn8FiA_0hpsLNVHFzW9KUfWI"
TELEGRAM_CHAT_ID = "-1003218422427"
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1437061730202157076/rd3pXwdqrK-QVnukQYk3oskNfMZC4KQvVOJQgVlWh9QRDWjt3LQrKc_g9fLuJ0nynWdO"
